from setuptools import setup, find_packages

setup(
    name="blackboxapi",
    version="0.5.0",
    packages=find_packages(),
    install_requires=[
        "requests>=2.32.3",
        "aiohttp>=3.10.10",
        "aiohappyeyeballs>=2.4.3",
        "Brotli>=1.1.0",
        "colorama>=0.4.6",
        "propcache>=0.2.0",
        "urllib3>=2.2.3",
        "pydantic>=2.9.2",
        "pyyaml>=6.0.2",
        "pillow>=11.0.0",
        "nest-asyncio>=1.6.0",
        "pycryptodome>=3.21.0",
        "typing_extensions>=4.12.2"
    ],
    python_requires=">=3.8",
    author="Keva1z",
    author_email="Keva1z@yandex.ru",
    description="Python library for Blackbox AI API integration with image support",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/Keva1z/blackboxapi",
    classifiers=[
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
)